### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by mimi89999** [apiote/Bimba#1]
Version: 1.0.2 F-Droid
Device: Samsung Galaxy S4 Mini
Android Version: LineageOS 14.1 (Android 7.1.2)

I see *Timetable is being downloaded* and just after I get the crash:
```
08-22 19:07:24.684  6799  6799 E SQLiteLog: (14) cannot open file at line 32456 of [bda77dda96]
08-22 19:07:24.684  6799  6799 E SQLiteLog: (14) os_unix.c:32456: (2) open(/data/user/0/ml.adamsprogs.bimba/files/timetable.db) - 
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: Failed to open database '/data/user/0/ml.adamsprogs.bimba/files/timetable.db'.
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at ml.adamsprogs.bimba.models.Timetable.readDbFile(Timetable.kt:28)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at ml.adamsprogs.bimba.models.Timetable.<init>(Timetable.kt:15)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at ml.adamsprogs.bimba.activities.SplashActivity.onCreate(SplashActivity.kt:13)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.app.Activity.performCreate(Activity.java:6684)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.os.Looper.loop(Looper.java:154)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at java.lang.reflect.Method.invoke(Native Method)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-22 19:07:24.686  6799  6799 E SQLiteDatabase: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-22 19:07:24.686  6799  6799 E Timetable: Cannot open database
```

**Comment by apiote** [comment]
I know.

The problem lies in latest timetable having been poorly scraped.

Scraper script is fixed, I scraped locally a working timetable.

Currently I’m unable to upload neither the script nor the timetable to my website (`cron` of which scraps the timetable, and from which Bimba updates the timetable) because my account got suspended.

**Comment by apiote** [comment]
I fixed the timetable for now.

You have to remove the old timetable database from the internal storage – so either remove app data in system settings or uninstall and install the app again. Then new timetable should be downloaded when You open the app next time.

**Comment by mimi89999** [comment]
Reinstalled Bimba. It works now. The timetable downloads and I end up with a black screen with a white search bar. What shall I do now? Looks like another issue.

**Comment by apiote** [comment]
By the time of Your comment, I assume it was night when You experienced what You’ve described. The screen is black at night and white during the day – it’s called Day-night Theme and it’s a feature.

Obviously, when You are presented with a searchbar only, the only option is to search. You can search for a stop, You’ll be presented with suggestions, and when You click on one, You’ll end up with a timetable for this stop. When You go online, You‘ll see the times according to the Virtual Monitor.

After all it’s a timetable app. May I ask what You’d expected?

**Comment by mimi89999** [comment]
I thought there would be a list of lines or a text inviting to search for a stop... But like that it is fine as well...

**Comment by apiote** [comment]
Thank You for the suggestion — placeholder in the searchbar will invite to search for a stop.
