### ISSUE TITLE
"Error. Try again later"

### ISSUE THREAD

**Issue by kuba-orlik** [apiote/Bimba#10]
After downloading the app and running it, it tries to download the timetable and quickly fails, displaying "Error. Try again later"

The logs say: 

```
(14) os_unix.c:32460: (2) open(/storage/3DB7-CD11/Android/data/ml.adamsprogs.bimba/files/timetable.db) -

Failed to open database '/storage/3DB7-CD11/Android/data/ml.adamsprogs.bimba/files/timetable.db'.
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
 at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
 at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
 at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
 at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
 at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
 at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
 at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:671)
 at ml.adamsprogs.bimba.models.Timetable$Companion.constructTimetable(Timetable.kt:40)
 at ml.adamsprogs.bimba.models.Timetable$Companion.getTimetable(Timetable.kt:21)
 at ml.adamsprogs.bimba.activities.NoDbActivity.onResume(NoDbActivity.kt:48)
 at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
 at android.app.Activity.performResume(Activity.java:6788)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6186)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by apiote** [comment]
Thank You.
The exception is expected: the app tries to open the timetable which doesn’t exist (yet) and catches this exception (it shows in logs, though—I don’t know why), and moves on to downloading the timetable. The problem was in downloading the timetable (which also catches an exception, but that one doesn’t show in logs—I don’t know why).

Anyway, 7fce24f should fix that. Actually, it’s a workaround that always uses https. But that works with my server (which is currently the only one).
